import crypto from "node:crypto";
import { SEASON_SHEET_ID, SEASON_TABS } from "@/lib/seasonSheets";
const SHEETS_SCOPE = "https://www.googleapis.com/auth/spreadsheets", TOKEN_URL = "https://oauth2.googleapis.com/token";
const base64Url = (value) => Buffer.from(value).toString("base64url");
const spreadsheetId = () => process.env.AVHL_SEASON_SHEET_ID || SEASON_SHEET_ID;
function credentials() { const clientEmail = String(process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL || "").trim(); const privateKey = String(process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY || "").replace(/\\n/g, "\n").trim(); if (!clientEmail || !privateKey) throw new Error("Google Sheets write credentials are not configured."); return { clientEmail, privateKey }; }
async function accessToken() { const { clientEmail, privateKey } = credentials(); const now = Math.floor(Date.now() / 1000); const unsigned = `${base64Url(JSON.stringify({ alg: "RS256", typ: "JWT" }))}.${base64Url(JSON.stringify({ iss: clientEmail, scope: SHEETS_SCOPE, aud: TOKEN_URL, iat: now, exp: now + 3600 }))}`; const signer = crypto.createSign("RSA-SHA256"); signer.update(unsigned); signer.end(); const assertion = `${unsigned}.${signer.sign(privateKey).toString("base64url")}`; const response = await fetch(TOKEN_URL, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer", assertion }), cache: "no-store" }); const payload = await response.json().catch(() => ({})); if (!response.ok || !payload.access_token) throw new Error(payload.error_description || payload.error || `Google OAuth returned HTTP ${response.status}`); return payload.access_token; }
async function sheetsRequest(path, options = {}) { const token = await accessToken(); const response = await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId()}${path}`, { ...options, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...(options.headers || {}) }, cache: "no-store" }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload?.error?.message || `Google Sheets API returned HTTP ${response.status}`); return payload; }
const a1Tab = (tab) => `'${String(tab).replace(/'/g, "''")}'`;
const columnARange = (tab) => `${a1Tab(tab)}!A:A`;
function lastUsedRow(values = []) { let last = 0; values.forEach((row, index) => { if (String(row?.[0] ?? "").trim() !== "") last = index + 1; }); return last; }
export async function getOfficialWriteState() { const tabs = [SEASON_TABS.teamStats, SEASON_TABS.skaterStats, SEASON_TABS.goalieStats]; const query = tabs.map((tab) => `ranges=${encodeURIComponent(columnARange(tab))}`).join("&"); const payload = await sheetsRequest(`/values:batchGet?majorDimension=ROWS&${query}`); const state = {}; tabs.forEach((tab, index) => { const values = payload.valueRanges?.[index]?.values || []; state[tab] = { gameIds: new Set(values.slice(1).map((row) => String(row?.[0] ?? "").trim()).filter(Boolean)), nextRow: Math.max(2, lastUsedRow(values) + 1) }; }); return state; }
const rangeForRows = (tab, startRow, rowCount, endColumn) => `${a1Tab(tab)}!A${startRow}:${endColumn}${startRow + rowCount - 1}`;
export async function writeOfficialGameRows({ gameId, teamRows, skaterRows, goalieRows }) { if (!teamRows?.length || !skaterRows?.length || !goalieRows?.length) throw new Error("Official game rows are incomplete."); const state = await getOfficialWriteState(); const id = String(gameId); for (const tab of [SEASON_TABS.teamStats, SEASON_TABS.skaterStats, SEASON_TABS.goalieStats]) if (state[tab].gameIds.has(id)) throw new Error(`Game ${id} has already been submitted to ${tab}.`); const data = [ { range: rangeForRows(SEASON_TABS.teamStats, state[SEASON_TABS.teamStats].nextRow, teamRows.length, "U"), majorDimension: "ROWS", values: teamRows }, { range: rangeForRows(SEASON_TABS.skaterStats, state[SEASON_TABS.skaterStats].nextRow, skaterRows.length, "W"), majorDimension: "ROWS", values: skaterRows }, { range: rangeForRows(SEASON_TABS.goalieStats, state[SEASON_TABS.goalieStats].nextRow, goalieRows.length, "R"), majorDimension: "ROWS", values: goalieRows } ]; const result = await sheetsRequest("/values:batchUpdate", { method: "POST", body: JSON.stringify({ valueInputOption: "RAW", data }) }); return { gameId: id, teamRows: teamRows.length, skaterRows: skaterRows.length, goalieRows: goalieRows.length, updatedRanges: result.responses?.map((r) => r.updatedRange) || [] }; }
