import { normalizePlayerId, secondsToClock } from "./seasonSheets.js";
const cleanFinish = (value) => ["REG", "OT", "SO"].includes(String(value || "REG").toUpperCase()) ? String(value || "REG").toUpperCase() : "REG";
const ratio = (a, b) => (Number(b) || 0) ? (Number(a) || 0) / (Number(b) || 0) : 0;
const resultFor = (score, opponentScore) => Number(score) > Number(opponentScore) ? "W" : "L";
function pimClock(minutes) { const totalSeconds = Math.max(0, Math.round((Number(minutes) || 0) * 60)); return `${String(Math.floor(totalSeconds / 60)).padStart(2, "0")}:${String(totalSeconds % 60).padStart(2, "0")}`; }
const goalieGaa = (goalsAgainst, toi) => (Number(toi) || 0) ? ((Number(goalsAgainst) || 0) * 3600) / (Number(toi) || 0) : 0;
function teamRowsForSide({ gameId, finish, packet, teamKey, opponentKey, homeAway }) { const team = packet[teamKey], opponent = packet[opponentKey], stats = packet.summary?.teamStats?.[team.id]; if (!team || !opponent || !stats) throw new Error(`Missing ${teamKey} team statistics.`); return [gameId,"SIM",team.abbreviation,team.fullName,opponent.abbreviation,homeAway,Number(team.score)||0,Number(opponent.score)||0,resultFor(team.score,opponent.score),finish,Number(stats.shots)||0,Number(stats.hits)||0,secondsToClock(stats.timeOnAttack),ratio(stats.passCompletions,stats.passAttempts),Number(stats.faceoffsWon)||0,pimClock(stats.penaltyMinutes),`${Number(stats.powerPlayGoals)||0}/${Number(stats.powerPlayOpportunities)||0}`,secondsToClock(stats.powerPlayTime),Number(stats.shorthandedGoals)||0,Number(stats.injuries)||0,Number(stats.manGamesLostProjected)||0]; }
function skaterRowsForSide({ gameId, packet, teamKey, opponentKey, homeAway }) { const team = packet[teamKey], opponent = packet[opponentKey], rows = packet.summary?.skaters?.[team.id]; if (!Array.isArray(rows)) throw new Error(`Missing ${teamKey} skater statistics.`); return rows.map((player) => { const fot=(Number(player.faceoffWins)||0)+(Number(player.faceoffLosses)||0), shots=Number(player.shots)||0; return [gameId,"SIM",team.abbreviation,opponent.abbreviation,homeAway,normalizePlayerId(player.avhlId||player.id),player.name||"",player.position||"",secondsToClock(player.toi),Number(player.goals)||0,Number(player.assists)||0,Number(player.points)||0,Number(player.plusMinus)||0,shots,shots?(Number(player.goals)||0)/shots:0,secondsToClock(player.ppToi),pimClock(player.penaltyMinutes),Number(player.hits)||0,Number(player.powerPlayGoals)||0,Number(player.shorthandedGoals)||0,fot,Number(player.faceoffWins)||0,fot?(Number(player.faceoffWins)||0)/fot:0]; }); }
function goalieRowsForSide({ gameId, packet, teamKey, opponentKey, homeAway }) { const team=packet[teamKey], opponent=packet[opponentKey], rows=packet.summary?.goalieRows?.[team.id]; if (!Array.isArray(rows)) throw new Error(`Missing ${teamKey} goalie statistics.`); return rows.map((goalie)=>{ const sa=Number(goalie.shotsAgainst)||0, sv=Number(goalie.saves)||0, ga=Number(goalie.goalsAgainst)||0, toi=Number(goalie.toi)||0; return [gameId,"SIM",team.abbreviation,opponent.abbreviation,homeAway,normalizePlayerId(goalie.avhlId||goalie.id),goalie.name||"",secondsToClock(toi),sa,sv,sa?sv/sa:0,ga,goalieGaa(ga,toi),Number(goalie.emptyNetGoals)||0,pimClock(goalie.penaltyMinutes),Number(goalie.goals)||0,Number(goalie.assists)||0,Number(goalie.points)||0]; }); }
export function buildOfficialSheetRows(gameId, packet) { const id=Number.parseInt(String(gameId),10); if(!Number.isInteger(id)||id<1||id>1640) throw new Error("Game number must be between 1 and 1640."); if(!packet?.away?.abbreviation||!packet?.home?.abbreviation||!packet?.summary) throw new Error("Official simulator data is incomplete."); if(Number(packet.away.score)===Number(packet.home.score)) throw new Error("A final official game cannot be tied."); const finish=cleanFinish(packet.finish); const teamRows=[teamRowsForSide({gameId:id,finish,packet,teamKey:"away",opponentKey:"home",homeAway:"A"}),teamRowsForSide({gameId:id,finish,packet,teamKey:"home",opponentKey:"away",homeAway:"H"})]; const skaterRows=[...skaterRowsForSide({gameId:id,packet,teamKey:"away",opponentKey:"home",homeAway:"A"}),...skaterRowsForSide({gameId:id,packet,teamKey:"home",opponentKey:"away",homeAway:"H"})]; const goalieRows=[...goalieRowsForSide({gameId:id,packet,teamKey:"away",opponentKey:"home",homeAway:"A"}),...goalieRowsForSide({gameId:id,packet,teamKey:"home",opponentKey:"away",homeAway:"H"})]; if(goalieRows.length<4) throw new Error("Both teams must include their starter and backup goalie rows."); return {teamRows,skaterRows,goalieRows,finish}; }
