const pct = (value, digits = 1) => `${((Number(value) || 0) * 100).toFixed(digits)}%`;
const savePct = (value) => (Number(value) || 0).toFixed(3);
const plusMinus = (value) => { const number = Number(value) || 0; return number > 0 ? `+${number}` : String(number); };
function clock(seconds) { const value = Math.max(0, Math.round(Number(seconds) || 0)); return `${Math.floor(value / 60)}:${String(value % 60).padStart(2, "0")}`; }
function dateLabel(value) { return value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(`${value}T12:00:00`)) : "—"; }
function StatCard({ label, value }) { return <div className="rounded-2xl border border-[#000B36]/10 bg-white p-4"><p className="text-2xl font-black tabular-nums">{value}</p><p className="mt-1 text-[9px] font-black uppercase tracking-[0.14em] text-[#000B36]/38">{label}</p></div>; }

export default function PlayerSeasonStatsSection({ goalie, stats, scheduleById }) {
  const gameRows = stats?.gameRows || [];
  return <div className="mt-8 rounded-3xl border border-[#000B36]/10 bg-white p-6 shadow-sm md:p-8"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#A90117]">2026–27 live statistics</p><h2 className="mt-1 text-3xl font-black">Current season</h2><p className="mt-2 text-sm font-semibold text-[#000B36]/45">Compiled from official game-by-game rows in the AVHL season workbook.</p></div>{stats?<>
    <div className={`mt-6 grid gap-3 sm:grid-cols-3 ${goalie?"lg:grid-cols-7":"lg:grid-cols-8"}`}>{(goalie?[[stats.gp,"GP"],[stats.dressed,"Dressed"],[clock(stats.toi),"Minutes"],[stats.shotsAgainst,"SA"],[stats.saves,"SV"],[savePct(stats.savePct),"SV%"],[(Number(stats.gaa)||0).toFixed(2),"GAA"]]:[[stats.gp,"GP"],[stats.goals,"Goals"],[stats.assists,"Assists"],[stats.points,"Points"],[plusMinus(stats.plusMinus),"+/-"],[stats.shots,"Shots"],[pct(stats.shotPct),"S%"],[stats.hits,"Hits"]]).map(([value,label])=><StatCard key={label} label={label} value={value}/>)}</div>
    {!goalie?<div className="mt-3 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[[clock(stats.toi),"TOI"],[clock(stats.ppToi),"PP TOI"],[stats.penaltyMinutes,"PIM"],[stats.powerPlayGoals,"PPG"],[stats.faceoffsWon,"FOW"],[pct(stats.faceoffPct),"FO%"]].map(([value,label])=><StatCard key={label} label={label} value={value}/>)}</div>:<div className="mt-3 grid gap-3 sm:grid-cols-3 lg:grid-cols-5">{[[stats.goalsAgainst,"GA"],[stats.emptyNetGoals,"ENG"],[stats.penaltyMinutes,"PIM"],[stats.goals,"G"],[stats.assists,"A"]].map(([value,label])=><StatCard key={label} label={label} value={value}/>)}</div>}
    <div className="mt-7 overflow-hidden rounded-2xl border border-[#000B36]/10"><div className="bg-[#F6F8FC] px-5 py-4"><h3 className="text-lg font-black">Game log</h3></div><div className="overflow-x-auto">{goalie?
      <table className="w-full min-w-[760px] text-sm"><thead className="bg-[#000B36] text-[10px] font-black uppercase tracking-[0.12em] text-white/70"><tr><th className="px-4 py-3 text-left">Game</th><th className="px-3 py-3 text-left">Matchup</th>{["MIN","SA","SV","SV%","GA","GAA"].map((h)=><th key={h} className="px-3 py-3 text-center">{h}</th>)}</tr></thead><tbody className="divide-y divide-[#000B36]/8">{gameRows.map((row)=>{const fixture=scheduleById[row.gameId],sv=row.shotsAgainst?row.saves/row.shotsAgainst:0,gaa=row.toi?(row.goalsAgainst*3600)/row.toi:0;return <tr key={row.gameId}><td className="px-4 py-3"><span className="font-black">#{row.gameId}</span><span className="ml-2 text-xs text-[#000B36]/40">{dateLabel(fixture?.date)}</span></td><td className="px-3 py-3 font-bold">{row.homeAway==="H"?"vs":"@"} {row.opponent}</td><td className="px-3 py-3 text-center">{clock(row.toi)}</td><td className="px-3 py-3 text-center">{row.shotsAgainst}</td><td className="px-3 py-3 text-center">{row.saves}</td><td className="px-3 py-3 text-center font-black">{savePct(sv)}</td><td className="px-3 py-3 text-center">{row.goalsAgainst}</td><td className="px-3 py-3 text-center">{gaa.toFixed(2)}</td></tr>;})}</tbody></table>:
      <table className="w-full min-w-[920px] text-sm"><thead className="bg-[#000B36] text-[10px] font-black uppercase tracking-[0.12em] text-white/70"><tr><th className="px-4 py-3 text-left">Game</th><th className="px-3 py-3 text-left">Matchup</th>{["MIN","G","A","PTS","+/-","S","Hits","FOW"].map((h)=><th key={h} className="px-3 py-3 text-center">{h}</th>)}</tr></thead><tbody className="divide-y divide-[#000B36]/8">{gameRows.map((row)=>{const fixture=scheduleById[row.gameId];return <tr key={row.gameId}><td className="px-4 py-3"><span className="font-black">#{row.gameId}</span><span className="ml-2 text-xs text-[#000B36]/40">{dateLabel(fixture?.date)}</span></td><td className="px-3 py-3 font-bold">{row.homeAway==="H"?"vs":"@"} {row.opponent}</td><td className="px-3 py-3 text-center">{clock(row.toi)}</td><td className="px-3 py-3 text-center">{row.goals}</td><td className="px-3 py-3 text-center">{row.assists}</td><td className="px-3 py-3 text-center font-black">{row.points}</td><td className="px-3 py-3 text-center">{plusMinus(row.plusMinus)}</td><td className="px-3 py-3 text-center">{row.shots}</td><td className="px-3 py-3 text-center">{row.hits}</td><td className="px-3 py-3 text-center">{row.faceoffsWon}</td></tr>;})}</tbody></table>}
    </div></div>
  </>:<div className="mt-6 rounded-2xl bg-[#F6F8FC] p-6"><p className="font-black">No 2026–27 game stats yet.</p><p className="mt-2 text-sm font-semibold text-[#000B36]/45">This section will populate automatically after official SIM submissions or SNS stats are entered.</p></div>}</div>;
}
