import Link from "next/link";

const pct = (value, digits = 1) => `${((Number(value) || 0) * 100).toFixed(digits)}%`;
const decimal = (value, digits = 1) => (Number(value) || 0).toFixed(digits);
const savePct = (value) => (Number(value) || 0).toFixed(3);
const plusMinus = (value) => { const number = Number(value) || 0; return number > 0 ? `+${number}` : String(number); };
function clock(seconds) { const value = Math.max(0, Math.round(Number(seconds) || 0)); return `${Math.floor(value / 60)}:${String(value % 60).padStart(2, "0")}`; }
function dateLabel(value) { return value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(new Date(`${value}T12:00:00`)) : "—"; }

export default function TeamSeasonStatsSection({ team, teamStats, skaters, goalies, scheduleById, playerDirectory = {} }) {
  const playerRows = [...skaters].sort((a, b) => b.points - a.points || b.goals - a.goals || a.name.localeCompare(b.name));
  const goalieRows = [...goalies].sort((a, b) => b.gp - a.gp || b.toi - a.toi || a.name.localeCompare(b.name));
  const games = teamStats?.gameRows || [];
  const record = teamStats ? `${teamStats.wins}-${teamStats.losses}-${teamStats.otl}` : "0-0-0";
  return (
    <section className="border-y border-[#000B36]/8 bg-white">
      <div className="mx-auto max-w-7xl px-6 py-14 md:px-8 md:py-20">
        <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-[#A90117]">2026–27 live statistics</p><h2 className="mt-2 text-3xl font-black tracking-tight md:text-4xl">Season stats</h2><p className="mt-3 max-w-2xl text-sm font-semibold leading-6 text-[#000B36]/52">Compiled from the official game-by-game Team, Skater, and Goalie Stats tabs.</p></div><Link href={`/schedule/${team.slug}`} className="rounded-full border border-[#000B36]/12 px-5 py-2.5 text-xs font-black uppercase tracking-wide hover:border-[#18BDFC]">Full schedule →</Link></div>
        <div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[[record,"Record"],[teamStats?.points??0,"Points"],[teamStats?.goalsFor??0,"Goals for"],[teamStats?.goalsAgainst??0,"Goals against"],[decimal(teamStats?.shotsPerGame||0),"Shots / game"],[pct(teamStats?.powerPlayPct||0),"Power play"]].map(([value,label])=><div key={label} className="rounded-2xl border border-[#000B36]/10 bg-[#F6F8FC] p-4"><p className="text-2xl font-black tabular-nums">{value}</p><p className="mt-1 text-[9px] font-black uppercase tracking-[0.14em] text-[#000B36]/38">{label}</p></div>)}</div>
        <div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[[decimal(teamStats?.hitsPerGame||0),"Hits / game"],[clock(teamStats?.timeOnAttackPerGame||0),"TOA / game"],[pct(teamStats?.passing||0),"Avg passing"],[decimal(teamStats?.faceoffsWonPerGame||0),"FOW / game"],[teamStats?.manGamesLost??0,"Man-games lost"]].map(([value,label])=><div key={label} className="rounded-2xl border border-[#000B36]/10 p-4"><p className="text-xl font-black tabular-nums">{value}</p><p className="mt-1 text-[9px] font-black uppercase tracking-[0.14em] text-[#000B36]/38">{label}</p></div>)}</div>

        <div className="mt-9 overflow-hidden rounded-3xl border border-[#000B36]/10"><div className="border-b border-[#000B36]/8 bg-[#F6F8FC] px-5 py-4"><h3 className="text-xl font-black">Skaters</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[1000px] border-collapse text-sm"><thead className="bg-[#000B36] text-[10px] font-black uppercase tracking-[0.12em] text-white/70"><tr><th className="px-5 py-3 text-left">Player</th>{["GP","G","A","PTS","+/-","S","S%","PIM","Hits","PPG","SHG","FOW","FO%","TOI"].map((h)=><th key={h} className="px-3 py-3 text-center">{h}</th>)}</tr></thead><tbody className="divide-y divide-[#000B36]/8">{playerRows.map((row)=>{const profile=playerDirectory[row.playerId]||{};const jersey=Number.isFinite(profile.number)?`#${profile.number} `:"";return <tr key={row.playerId}><td className="px-5 py-3"><Link href={`/players/${row.playerId}`} className="font-black hover:text-[#A90117]">{jersey}{row.name}</Link><span className="ml-2 text-[10px] font-bold text-[#000B36]/35">{row.position||profile.position||"—"}</span></td><td className="px-3 py-3 text-center">{row.gp}</td><td className="px-3 py-3 text-center">{row.goals}</td><td className="px-3 py-3 text-center">{row.assists}</td><td className="px-3 py-3 text-center font-black">{row.points}</td><td className="px-3 py-3 text-center">{plusMinus(row.plusMinus)}</td><td className="px-3 py-3 text-center">{row.shots}</td><td className="px-3 py-3 text-center">{pct(row.shotPct)}</td><td className="px-3 py-3 text-center">{row.penaltyMinutes}</td><td className="px-3 py-3 text-center">{row.hits}</td><td className="px-3 py-3 text-center">{row.powerPlayGoals}</td><td className="px-3 py-3 text-center">{row.shorthandedGoals}</td><td className="px-3 py-3 text-center">{row.faceoffsWon}</td><td className="px-3 py-3 text-center">{pct(row.faceoffPct)}</td><td className="px-3 py-3 text-center">{clock(row.toi)}</td></tr>})}</tbody></table></div>{playerRows.length===0?<p className="p-6 text-sm font-semibold text-[#000B36]/45">No skater stats have been recorded yet.</p>:null}</div>

        <div className="mt-6 overflow-hidden rounded-3xl border border-[#000B36]/10"><div className="border-b border-[#000B36]/8 bg-[#F6F8FC] px-5 py-4"><h3 className="text-xl font-black">Goalies</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-sm"><thead className="bg-[#000B36] text-[10px] font-black uppercase tracking-[0.12em] text-white/70"><tr><th className="px-5 py-3 text-left">Goalie</th>{["GP","Dressed","MIN","SA","SV","SV%","GA","GAA","ENG","PTS"].map((h)=><th key={h} className="px-3 py-3 text-center">{h}</th>)}</tr></thead><tbody className="divide-y divide-[#000B36]/8">{goalieRows.map((row)=>{const profile=playerDirectory[row.playerId]||{};const jersey=Number.isFinite(profile.number)?`#${profile.number} `:"";return <tr key={row.playerId}><td className="px-5 py-3"><Link href={`/players/${row.playerId}`} className="font-black hover:text-[#A90117]">{jersey}{row.name}</Link><span className="ml-2 text-[10px] font-bold text-[#000B36]/35">G</span></td><td className="px-3 py-3 text-center">{row.gp}</td><td className="px-3 py-3 text-center">{row.dressed}</td><td className="px-3 py-3 text-center">{clock(row.toi)}</td><td className="px-3 py-3 text-center">{row.shotsAgainst}</td><td className="px-3 py-3 text-center">{row.saves}</td><td className="px-3 py-3 text-center font-black">{savePct(row.savePct)}</td><td className="px-3 py-3 text-center">{row.goalsAgainst}</td><td className="px-3 py-3 text-center">{(Number(row.gaa)||0).toFixed(2)}</td><td className="px-3 py-3 text-center">{row.emptyNetGoals}</td><td className="px-3 py-3 text-center">{row.points}</td></tr>})}</tbody></table></div>{goalieRows.length===0?<p className="p-6 text-sm font-semibold text-[#000B36]/45">No goalie stats have been recorded yet.</p>:null}</div>

        <div className="mt-6 overflow-hidden rounded-3xl border border-[#000B36]/10"><div className="border-b border-[#000B36]/8 bg-[#F6F8FC] px-5 py-4"><h3 className="text-xl font-black">Game log</h3></div>{games.length?<div className="divide-y divide-[#000B36]/8">{games.map((row)=>{const fixture=scheduleById[row.gameId];return <div key={row.gameId} className="grid gap-2 px-5 py-4 text-sm sm:grid-cols-[90px_1fr_auto_auto] sm:items-center"><span className="text-xs font-black text-[#000B36]/45">{dateLabel(fixture?.date)}</span><span className="font-black">{row.homeAway==="H"?"vs":"@"} {row.opponent}</span><span className="font-black">{row.result} {row.score}–{row.oppScore}{row.finish!=="REG"?` ${row.finish}`:""}</span><span className="text-xs font-bold text-[#000B36]/45">Game {row.gameId}</span></div>;})}</div>:<p className="p-6 text-sm font-semibold text-[#000B36]/45">No games have been recorded yet.</p>}</div>
      </div>
    </section>
  );
}
